from static.coordinate import Coordinate

RIGHT = Coordinate((0, 1))
LEFT = Coordinate((0, -1))
UP = Coordinate((-1, 0))
DOWN = Coordinate((1, 0))

REMOVAL_SUBTLE_CHANCE = 0.20
REMOVAL_NOTICEABLE_CHANCE = 0.40
REMOVAL_INTENSE_CHANCE = 0.60
REMOVAL_EXTREME_CHANCE = 0.80

MAX_CHAOS = 4

MAX_AGGRO = 4
MILD_MOVE_CHANCE = 0.25
MODERATE_MOVE_CHANCE = 0.5
STRONG_MOVE_CHANCE = 0.75
EXTERME_MOVE_CHANCE = 0.90
